name: Tests suit

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build project
        run: yarn install && yarn build
      - name: Unit tests
        run: yarn jest:run
      - name: Cypress App tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: http://localhost:3000
          browser: chrome
          config: baseUrl=http://localhost:3000,integrationFolder=cypress/integration,testFiles=**/*.*
      - name: Cypress Storybook tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn storybook:start
          wait-on: http://localhost:6006
          browser: chrome
          config: baseUrl=http://localhost:6006,integrationFolder=playground,testFiles=**/*.e2e.*
      
